import About from "./About";
import Blog from "./Blog";
import Contact from "./Contact";
import Home from "./Home";
import Pricing from "./Pricing";
import Services from "./Services";
import Error from "./Error";
import Header from "./Header";
import Footer from "./Footer";
export { About, Blog, Contact, Home, Pricing, Services, Error, Header, Footer };
